name: 'Dismiss code reviews not from x'
description: 'Dismiss code reviews on pull requests from anyone not in the list.'
branding:
  icon: 'thumbs-down'
  color: 'red'
author: 'peckjon'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret or PATH'
    required: true
  x:
    description: 'The reviewers'
    required: true
  dismiss-message:
    description: 'Dismiss message'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
